.travis.yml

Kick off travis build via PR...

Try and enable a cross-run travis pip cache

---

alembic/versions/4c89b299ffb0_remove_ocid_cell_id_column.py
alembic/versions/fe2cfea89f5_change_cell_primary_key_to_composite_key.py
ichnaea/app.py
ichnaea/backup/tests.py
ichnaea/content/stats.py
ichnaea/export/tasks.py
ichnaea/export/tests.py
ichnaea/models.py
ichnaea/service/monitor/views.py
ichnaea/tests/test_models.py

- Remove primary key ID from cell and cell_blacklist tables
- Change (radio, mcc, mnc, lac, cid) to primary key
- Update logic to remove references to cell.id
- Update tests accordingly
r? @hannosch

Remove Cell/CellBlacklist ID field #353

---

docs/internal_api/service/locate.rst
ichnaea/service/geolocate/tests.py
ichnaea/service/locate.py
ichnaea/service/search/tests/test_views.py
ichnaea/service/tests/test_locate.py

- Make a clear distinction between an individual search provider (cell, cell lac, wifi, geoip) and a location searcher which combines them
- Add a test to hit the OCIDCell table
- Remove unnecessary stats logging
@hannosch r?  The Big One.

Refactor search logic #400

---

docs/deploy.rst

requirements/circus.txt for Circus

---

docs/deploy.rst

circusd run command as code-block

---

ichnaea/data/report.py
ichnaea/data/tasks.py
ichnaea/locate/provider.py
ichnaea/locate/searcher.py
ichnaea/locate/stats.py
ichnaea/locate/tests/test_provider.py
ichnaea/locate/tests/test_searcher.py
ichnaea/models/api.py
ichnaea/service/base.py
ichnaea/service/base_submit.py
ichnaea/service/country/views.py
ichnaea/service/geolocate/views.py
ichnaea/service/geosubmit/views.py
ichnaea/service/search/views.py
ichnaea/service/submit/views.py

-Query the API Key object in the check_api_key decorator
-Pass that object to the decorated view
-If no API Key object can be found, pass in an empty object

Refactor API Key Logic #425

---

alembic/versions/e9c1224f6bb_add_fallback_flag_to_api_key.py
ichnaea.ini
ichnaea/locate/location.py
ichnaea/locate/provider.py
ichnaea/locate/searcher.py
ichnaea/locate/tests/test_provider.py
ichnaea/locate/tests/test_searcher.py
ichnaea/models/api.py
ichnaea/service/country/views.py
ichnaea/service/geolocate/views.py
ichnaea/service/search/tests.py
ichnaea/service/search/views.py
ichnaea/tests/base.py

- Add FallbackProvider
- Add allow_fallback to ApiKey
- Add fallback parameters to ichnaea.ini
- Add should_locate method to provider/searcher contract
- Add tests

Add Fallback Provider #421

---

ichnaea/__init__.py
ichnaea/locate/tests/test_provider.py
ichnaea/locate/tests/test_searcher.py
ichnaea/tests/base.py
ichnaea/tests/test_geoip.py
ichnaea/tests/test_rate_limit.py
ichnaea/webapp/tests.py

- Override proper setup/teardown methods
- Remove custom setup/teardown methods
- Update test classes

Use super in test cases #434

---

.travis.yml
CHANGES.rst
requirements/prod.txt

Add scipy.

---

README.rst

Changed word flow of two sentences for improved readability.

Improved Word Flow

---

ichnaea/content/templates/api.pt

add verbiage about suspension of API key issuance

Suspending API key issuance

---

ichnaea/data/public.py

The header row was using '\n', while the spec and the rest of the code used '\r\n'.

fix line separator issues in public csv exporter

---

docker/run_web.sh
docs/install/config.rst
ichnaea/webapp/gunicorn_settings.py
ichnaea/webapp/tests.py

This reworks the gunicorn setup exposing many of the settings as
environment variables and adding it to the documentation.
Fixes #891

Add gunicorn settings

---

ichnaea/conf.py
ichnaea/log.py

Add STATSD_PORT to configuration

---

docs/metrics.rst

This fixes the docs after changes made in #944.

Update docs regarding change in locate.fallback.lookup* metrics

---

docs/configure.rst

Add documentation for SQLALCHEMY_URL

---

ichnaea/api/locate/tests/test_locate_v1.py

This may help diagnose the intermittent failure in #921

Provide more info when test_blue_seen fails

---

docker/config/local_dev.env
ichnaea/conf.py
ichnaea/log.py

This adds a `LOGGING_LEVEL` setting to make it easier to debug things.
Fixes #966

Add a LOGGING_LEVEL setting

---

ichnaea/scripts/apikey.py
ichnaea/util.py

This adds a maxreq option to the create subcommand. If it's not
specified, it sets the maxreq to 100.
This also reworks argument parsing switching from argparse to click.
Fixes #992
To test:
```
$ make shell
app@9a3fb08b6f79:/app$ ./ichnaea/scripts/apikey.py 
Usage: apikey.py [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
create  Create a new api key.
list    List all api keys in db.
show    Print api key details to stdout.
app@9a3fb08b6f79:/app$ ./ichnaea/scripts/apikey.py create fish
Created API key: 'fish'
app@9a3fb08b6f79:/app$ ./ichnaea/scripts/apikey.py create --maxreq=10000 fish2
Created API key: 'fish2'
app@9a3fb08b6f79:/app$ ./ichnaea/scripts/apikey.py list
2 api keys.
valid_key                            | allow_fallback | allow_locate | …
```

Add maxreq option to "apikey.py create"

---

ichnaea/data/tests/test_station.py

Use ``pytest.mark.parametrize`` instead of a for loop for the two main types of observation reports.
This dedents the test code, which can mostly be hidden if whitespace is ignored, but some lines are also reformatted with Black.
There are no test changes except for ``test_new``, which now expects one set of metrics per test run instead of two sets, one for each report type.
I did this in preparation of writing a failing test for issue #990, but it appears that this is a database-level issue, not an application issue, so I wasn't able to write a failing unit test. This still feels like a useful refactor, however.

Use pytest.mark.parametrize instead of for loops

---

ichnaea/api/locate/cell.py

This catches one I missed in the previous pass.

bug 1598325: fix None comparison error

---

bin/release.py
setup.cfg

This adds a release script and corresponding configuration so we can automate releases more.
Fixes #976

976: Add release script and configuration

---

ichnaea/taskapp/config.py

We changed the batch size from 100 to 500 yesterday and that didn't affect the graphs in a noticeable way. It also didn't seem to affect other things, so I think it's safe to increase it more.

bug 1600706: increase update_incoming batch size to 5000

---

ichnaea/data/area.py

With PR #1057 deployed to stage, there are more deadlocks than I expected when updating the cellarea tables. My guess is that this is because the ``SELECT ... FOR UPDATE`` is done inside the loop, so that two tasks working on the same rows may get partially through processing before they try to update the same rows and deadlock.
This PR locks all the cellarea rows at the start of processing, so that overlapping tasks will pause when getting a lock, making them sequential. It makes cellarea row locking more like station row locking.
An alternate implementation would process the IDs in sorted order. The lock contention would happen when the overlap occurs, but the risk of deadlock would be eliminated. However, in some cases this would result in some work occurring (selecting and processing …

991: Lock cellarea rows early to avoid deadlocks

---

.github/CODEOWNERS

This will automate assigning jwhitlock to code review.

Setup CODEOWNERS

---

ichnaea/log.py
ichnaea/scripts/datamap.py
ichnaea/scripts/sentry_test.py
ichnaea/taskapp/config.py
ichnaea/webapp/config.py

Not actually tested with Sentry itself, but this seems to pass CI tests.

Use tags to distinguish different apps in Sentry

---

docs/metrics.rst
ichnaea/taskapp/config.py

@jwhitlock I have made the changes as mentioned in issue #1408
Is there anything I can add?

removed celery_incoming queue #1408

---

.gitattributes

This should have been part of PR #1430.

Update .gitattributes for single requirements.txt

---

docker.make
docker/node/npm-shrinkwrap.json

Two updates to packaging systems:
* Update `npm-shrinkwrap.json` to ``"lockfileVersion": 2``
* Remove ``--use-feature=2020-resolver`` from pip, since it now gives a warning

Packaging updates

---

ichnaea/content/templates/contact.pt

Re-arrange the tags so it is valid HTML as well, and remove the whitespace from the ``<pre>`` tag.

bug 1738703: Update legal address

---

.circleci/config.yml

This PR includes some CircleCI build changes that were useful from PR #1762, even though we're not going to create multi-platform images at this time.

Update CircleCI build
