ichnaea.ini
ichnaea/locate/provider.py
ichnaea/locate/tests/test_provider.py
ichnaea/service/search/tests.py
ichnaea/tests/base.py

- When we receive only a single cell tower, cache the results
- Add tests
@hannosch r?

Cache single cell results for fallback #421

---

ichnaea/locate/provider.py
ichnaea/models/__init__.py
ichnaea/models/observation.py
ichnaea/service/geolocate/tests.py
ichnaea/service/search/tests.py

- Create CellAreaLookup and ValidCellAreaKeySchema
- Abstract out schema validator from Cell providers
- Add tests to v1 and v2 APIs

Allow v1/v2 API queries without CID #440

---

ichnaea/locate/location.py
ichnaea/locate/provider.py
ichnaea/locate/searcher.py
ichnaea/locate/tests/test_provider.py
ichnaea/locate/tests/test_searcher.py
ichnaea/service/base_locate.py
ichnaea/service/geolocate/schema.py
ichnaea/service/geolocate/tests.py
ichnaea/service/schema.py
ichnaea/service/search/schema.py
ichnaea/service/search/tests.py
ichnaea/service/search/views.py

- Accept lacf/ipf flags in search api
- Accept lacf/ipf flags in search providers
- Pass lacf/ipf flags to fallback provider
- Add tests

Add explicit fallback choices to geolocate API #438

---

ichnaea/api/error.py
ichnaea/api/locate/country/views.py
ichnaea/api/locate/locate_v1/schema.py
ichnaea/api/locate/locate_v1/tests.py
ichnaea/api/locate/locate_v1/views.py
ichnaea/api/locate/locate_v2/schema.py
ichnaea/api/locate/locate_v2/tests.py
ichnaea/api/locate/locate_v2/views.py
ichnaea/api/locate/schema.py
ichnaea/api/locate/views.py
ichnaea/api/schema.py
ichnaea/api/submit/submit_v1/tests.py
ichnaea/api/submit/views.py
ichnaea/api/tests.py
ichnaea/api/views.py

This is still split into separate commits in case we need to isolate and revert any specific change, should make it easier to understand each step.  This adds the Internal Mapping types, converts all of the request schemas to use them, and removes the Transform objects.
@hannosch r?

Replace LocateTransform with an internal class based representation #444

---

docs/api/index.rst

The documentation for requesting an API key was updated to reference
HTML5 API and the default of a 100k requests per day limit.

Updated API key documentation.

---

.pyup.yml

Instead of opening a pyup PR every day, open one for each dependency. This should reduce the traffic from a new PR every day, plus the noise from auto-closed PRs.

Disable scheduled pyup updates

---

.circleci/config.yml

Ichnaea uses ``DOCKER_USER`` and ``DOCKER_PASS``, while Socorro (where the code was copied from) uses ``DOCKER_USERNAME`` and ``DOCKER_PASSWORD``. Update to use Ichnaea's names.

Fix environment variable names for dockerhub credentials

---

.circleci/config.yml

``make build`` now tags the built image as ~``ichnaea_node:latest``~ ``local/ichnaea_app`` rather than ``mozilla/location``. Fix the circleci build step that that re-tags and pushes to dockerhub.
Follow-on work for issue #828.
**Update**: Force push to fix local tag name, commit comment.

Update docker tagging for "make build" target

---

docs/api/index.rst

Add a sentence to the document source that was already applied to the published documents in db92219eafc621db7053e6f63a7259fdb93536c4.

Add service eval note to API docs

---

docker/config/my.env.dist
docs/install/config.rst

This fleshes out the documentation on the Mapbox API token so it's
clearer.
Fixes #848

Add docs for Mapbox API token

---

docs/conf.py

Adding a mock for the shapely module allows ReadTheDocs to build the
docs even though Shapely isn't installed.
Fixes #859.

Add mock for shapely module

---

.gitignore
.gitmodules

Remove the built HTML documents submodule. Documents can still be built locally with `make docs`, but they will be ignored by git.
Part of #859.

Remove the built docs submodule

---

ichnaea/data/area.py
ichnaea/data/datamap.py
ichnaea/data/station.py
ichnaea/data/stats.py
ichnaea/db.py
ichnaea/log.py
ichnaea/tests/test_db.py
ichnaea/webapp/monitor.py

Adjust the code to reflect features added in SQLAlchemy 1.2 and 1.3, and remove the related custom code and tests.
A new option ``create_engine(pool_pre_ping=True)`` tests if a connection has been disconnected by the server before using it, replacing custom event handler ``check_connection``.
A similar "ping" function is used to determine that the database is available in the ``__heartbeat__`` view. This code is moved from the custom session to the view, so that the standard SQLAlchemy session class can be used.
A MySQL-specific ``INSERT`` clause, ``ON DUPLICATE KEY UPDATE``, was used to avoid errors when an ``INSERT`` refers to an existing key. This feels like overkill, since the code usually checks for existence with a ``SELECT``, but it could have been added based on real-world errors. …

Update SQLAlchemy code for 1.2, 1.3

---

ichnaea/db.py
ichnaea/webapp/config.py
ichnaea/webapp/monitor.py

Previously, a ``Database.ping()`` method was used to test the database connection when configuring the webapp. This was removed in the previous PR #892 (fixing #887) because it appeared to be unused, based on a code search and tests passing.
Instead of bringing ``.ping()`` back for a single caller, add a function ``ichnaea.db.ping_session()``, which can be used to test the connectivity of a database session. This is now used when configuring the webapp and when calling the ``__heartbeat__`` endpoint.

Fix database ping in webapp startup

---

ichnaea/conftest.py

The one user of ``monkey_session`` (``map_config``) was removed in PR #894, so
removing ``monkey_session`` as well. It appears the same functionality can
be accomplished by using the [monkeypatch fixture](https://docs.pytest.org/en/latest/reference.html#monkeypatch) in a derived fixture, so we don't need to keep this implementation around just in case.

Remove monkey_session fixture

---

ichnaea/alembic/versions/000000000000_base.py
ichnaea/api/key.py
ichnaea/conf.py
ichnaea/scripts/apikey.py
ichnaea/scripts/db.py
ichnaea/util.py

This implements a basic apikey manipulation cli that lets you list keys, show key details, and create keys.
In doing that, I removed the code in the base migration that creates database users and a test key. Seems like it's safer if both of them are created explicitly with intention rather than accidentally by running db migrations.
This is part of issue #503. I figured I'd break it up into parts as I finished them rather than one big sample data code dump.
To test:
1. `make build`
2. `make setup`
3. `make test` to verify tests still work
4. `docker-compose run app shell ./ichnaea/scripts/apikey.py` and play with that
That `docker-compose` line is a bit much. With Socorro, we wrote a `socorro-cmd` as a frontend for all the scripts. I removed the `dev` script from this repo that sort of …

Implement basic apikey manipulation cli

---

CONTRIBUTING.rst

irc.mozilla.org is going away soon. This removes references to it.

Remove IRC references

---

docker/config/local_dev.env
docker/run_scheduler.sh
docker/run_worker.sh
ichnaea/conf.py
ichnaea/log.py
ichnaea/taskapp/app.py
ichnaea/taskapp/config.py
ichnaea/taskapp/settings.py

This adds a `CELERY_WORKER_CONCURRENCY` setting.
This redoes Celery logging configuration so it uses the same configuration as the rest of Ichnaea including whether or not to use mozlog.
Fixes #909.
Fixes #913.
To test:
1. Run `make runcelery`.
Should spin up one celery worker with concurrency: 1. You can tell by looking at the output when it spits out a `[config]` section to the right of a giant ASCII C.
Logging output should look "normal" for the scheduler and worker. Like this:
```
worker_1     | 2019-10-02 15:23:27,433 INFO  [celery.app.trace] - Task ichnaea.data.tasks.update_incoming[7a798f9e-7b81-4f56-b537-9979cfa60cd6] succeeded in 0.061439532990334556s: None
```
2. Add `CELERY_WORKER_CONCURRENCY=2` and `LOCAL_DEV_ENV=False` to `my.env` and then run `make runcelery`.
Should spin up …

Add CELERY_WORKER_CONCURRENCY setting and fix Celery logging

---

Dockerfile
docker/run_lint.sh

This updates the image we're using to Python 3.7.4. That's the current latest version available:
https://hub.docker.com/_/python?tab=tags&page=1&name=3.7
To test:
1. `make test`
2. `make lintfix`
3. `make lint`
4. `make run` and `make runcelery`
Everything seems fine. I think we might have hit issues before we updated all the requirements and renamed the "async" module. But now that we've done that, this is pretty straight-forward.
Fixes #934

Update to Python 3.7

---

Makefile

When running ``make mysql``, connect to the ``location`` database, so that a ``connect location`` is not needed for querying the regular database.

make mysql: connect to the location database

---

Makefile
bin/test_env.sh
ichnaea/data/stats.py
ichnaea/data/tests/test_stats.py

MySQL returns the number of rows affected by an ``UPDATE``, and ``bulk_update_mappings`` raises a ``StaleDataError`` if the affected rows are less than the rows sent.  This means that the update fails if the radio count is the same for any region. Instead, return to using the ORM methods, which sends several ``UPDATE``s, but only when the data changes.
Without this change, the new test ``test_update_no_change`` fails when ``update_statregion`` is called with no changes to the ``CellArea`` counts:
```
...
File "/app/ichnaea/data/stats.py", line 156, in _update_stats
session.bulk_update_mappings(RegionStat, updates)
File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2849, in bulk_update_mappings
mapper, mappings, True, False, False, False, False
File …
```

update_statregion: Use ORM, not bulk_*_mappings

---

docs/api/submit.rst

When I removed the deprecated `/v1/search/` API endpoint code and documentation, I didn't realize the documentation for the `/v1/submit/` API endpoint referred to it for the field definitions.
This adds the field definitions to the `/v1/submit/` API endpoint.

Add field definitions for /v1/submit/ API docs

---

ichnaea/api/locate/tests/__init__.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/submit/tests/__init__.py

Issue #921 tracks a test that occasionally fails (1-2 times a week) with no relevant code changes. This PR makes two changes:
* Use ``pytest`` rich ``assert`` in ``ichnaea/api/locate/tests/base.py`` and ``ichnaea/api/submit/tests/base.py``. This will tell us how many items have been added to the ``update_incoming``, which is expected to be empty. The shared testing code in these files has been skipped because they are named ``base.py`` rather than ``test_base.py`` or ``base_test.py``. This is a smaller change than renaming the files, and avoids confusion with ``ichnaea/models/tests/test_base.py``.
* Confirm that the data queue is empty at the start of the test, so that we know whether there is a test setup issue or the API view is queuing the report for further processing.

Investigate occasional test failure in the locate API

---

ichnaea/data/monitor.py
ichnaea/data/tasks.py
ichnaea/data/tests/test_monitor.py
ichnaea/taskapp/config.py

This re-adds the monitor queue size task. As MLS handles larger loads, the data queues can back up and if we're not able to see them, we can't do anything about it.
Fixes #947.

Re-add monitor queue size task

---

ichnaea/async/config.py

This fixes the `celery_app.all_queues` set so it includes the data queues. That way data queue sizes are sent as gauge metrics.
Fixes #947

Fix monitoring data queue sizes

---

ichnaea/data/area.py
ichnaea/data/tests/test_area.py

When importing the full cell export, a ``TypeError`` is raised when creating a cell area for some cell groups, due to changes in Python 3.x around comparing to ``None``. This PR avoids the ``TypeError`` and makes the code work like it did in Python 2.6.
In Python 2.6, you can sort ``None`` versus strings, and ``None`` is always less than a string:
```python
>>> sorted(['c', 'a', 'b', '', None])
[None, '', 'a', 'b', 'c']
```
In Python 3.7, it is a ``TypeError`` to compare ``None`` and other values:
```python
>>> sorted(['c', 'a', 'b', '', None])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
This can happen when the ``CellAreaUpdater`` is trying to determine the region for a group of cells …

Test, fix cell area region algorithm when cell regions are None

---

ichnaea/webapp/monitor.py
ichnaea/webapp/tests.py

This adds the alembic heads to `/__hearbeat__`. This lets us see what the
current heads are in a server environment.
Fixes #956

Add alembic heads to /__heartbeat__

---

docs/metrics.rst

When exploring metrics in Grafana, it is helpful to go from an alphabetical list of metric names to the detailed documentation for that metric.
I was expecting to find that the document was out of date, but it is actually a good reflection of the metrics code. There are no documented metrics that aren't omitted, and no emitted metrics that aren't documented. I left the note ``2019-09-24: This needs to be updated``, but I believe the docs are accurate, and I'd support removing it.
I'd want to rewrite this documentation. I don't find the purpose-based organization to be very helpful, and I'd like to get away from the notation ``key#tag1=value1,tag2=value2``. I'm holding back on a rewrite because 1) we should focus on the new infrastructure work, and 2) @willkg has been thinking of ways to …

Add table of contents to metrics doc

---

docs/metrics.rst
ichnaea/api/locate/fallback.py
ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_fallback.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/locate/tests/test_region_v1.py
ichnaea/api/submit/tests/base.py
ichnaea/content/tests/test_views.py
ichnaea/data/export.py
ichnaea/data/tests/test_export.py
ichnaea/log.py

This PR creates new metrics for timing values, so that we are not using the same metric name for a counter and a timer:
* ``data.export.upload`` → ``data.export.upload.timing``
* ``request`` → ``request.timing``
The counters continue sending to the original names, ``data.export.upload`` and ``request``.
This is the fix to #960 that requires the least code changes. For consistency, I also changed two metrics to use the same naming convention:
* ``locate.fallback.lookup_timing`` → ``locate.fallback.lookup.timing``
* ``locate.fallback.lookup_count`` → ``locate.fallback.lookup``
This is not the only possible naming scheme, and I'm open to suggestions for other ones.

Split counter and timer metrics

---

docker/run_web.sh
ichnaea/webapp/app.py

This improves the ability to debug the webapp startup in server
environments where startup issues are masked by gunicorn running the
webapp in a separate worker process. Now when the webapp container is
started, it runs a "check" to see if things can start up, and then
proceeds to run the webapp in gunicorn.
This helps fix issue #967.

Improve webapp startup debugging

---

ichnaea/log.py
version.json

If there's no tag, use the git commit as the release in sentry
reporting. This makes it easier to figure out bugs when we're
auto-deploying to stage when things land in the master branch.
Part of issue #963.

Fix sentry reporting to use git sha for release

---

ichnaea/util.py
ichnaea/webapp/tests.py

Dockerflow doesn't have a "tag" key, so there shouldn't be one in `/__version__`.
Fixes #980

Remove "tag" from /__version__ data

---

ichnaea/models/cell.py

"umts" is the deprecated name for WCDMA stations. This brings the JSON sample in line with the surrounding documentation.
This addresses some of #989.

Change "umts" to "wcdma" in models docstring

---

docs/api/index.rst

The document titles, like "Geosubmit: /v1/geosubmit (DEPRECATED)", no longer work as the link text, making the [History section](https://ichnaea.readthedocs.io/en/latest/api/index.html#history) nonsensical: 
> The service first offered the custom /v1/search/ [Submit: /v1/submit (DEPRECATED)](https://ichnaea.readthedocs.io/en/latest/api/submit.html#api-submit) APIs. Later it was decided to also implement the [Geolocate: /v1/geolocate](https://ichnaea.readthedocs.io/en/latest/api/geolocate.html#api-geolocate) API to lessen the burden on clients that want to support multiple location services. As an extension to this the [Geosubmit: /v1/geosubmit (DEPRECATED)](https://ichnaea.readthedocs.io/en/latest/api/geosubmit.html#api-geosubmit) API was added to offer a consistent way to contribute back …

Update API History section

---

ichnaea/api/submit/tests/test_submit_v0.py
ichnaea/data/public.py
ichnaea/data/tests/test_public.py
ichnaea/models/constants.py
ichnaea/models/tests/test_cell.py
ichnaea/models/tests/test_observation.py

``Radio.umts`` was the deprecated alias for ``Radio.wcdma``. The deprecated APIs still refer to this station type as "umts", and ``UMTS`` is used in the public export, but otherwise the code refers to it as ``wcdma`` now.
The largest changes are to the public export tests, many of which I wrote for the new ``load_cell_data.py`` feature. This may explain why I'm personally invested in removing as much "umts" as I can. 😁
This should fix #989. It replaces a smaller change in #999.

Remove Radio.umts

---

.circleci/config.yml

CircleCI doesn't run builds on new tags by default. This enables that.

Enable build-on-tag in CircleCI

---

ichnaea/taskapp/config.py

This will cause a single celery task to process 500 rather than 100. Overall, this will reduce the amount of bookkeeping done per `update_incoming` item. The mean time for executing an `update_incoming`
task is pretty small compared to the other tasks, so this seems like a safe try.

bug 1600706: change update_incoming batch size from 100 to 500

---

ichnaea/conftest.py
ichnaea/scripts/tests/test_datamap.py
ichnaea/scripts/tests/test_dump.py

After removing the alternate database drivers, the two session fixtures are identical, and tests using the ``sync_session`` fixture work just as well with the more common ``session`` fixture.

Replace sync_session fixture with session

---

docs/algo/observations.rst
docs/metrics.rst
ichnaea/data/station.py
ichnaea/data/tests/test_station.py
ichnaea/db.py

In [PyMySQL 0.9.0](https://github.com/PyMySQL/PyMySQL/blob/master/CHANGELOG#L39), ``LOCK_DEADLOCK`` changed from an internal error to an operational error. This also changes the SQLAlchemy error class used to wrap it. This broke the deadlock handler, and we started to get many more of these when the latest code went to production.
This PR updates the handler to only look at the MySQL error code, and be more flexible about the error class used to report it. It also increments a metric ``data.station.dberror``, to allow us to track how handled deadlocks are affected by other data pipeline changes. I also added some tests to cover this behaviour, that may have caught this change.
I struggled with some weirdness around testing code that sends a ``ROLLBACK``, such as this code when detecting …

Fix StationUpdate deadlock handler and track handled deadlocks

---

ichnaea/data/station.py

SQLAlchemy wraps database exceptions, like a deadlock, in ``StatementError``, and passes the original exception in ``.orig``. Other exceptions, derived from the more generic ``SQLAlchemyError``, are possible, such as a ``StaleDataError``.
This is follow-on work for issue #991 and issue #990.

Restrict SQLAlchemy exception handler

---

ichnaea/api/locate/cell.py
ichnaea/api/locate/internal.py
ichnaea/api/locate/mac.py
ichnaea/api/locate/tests/test_locate_v1.py

numpy strips trailing ``NULL`` characters (``0x00``) from byte strings ([numpy issue 8089](https://github.com/numpy/numpy/issues/8089)). This can cause stations to be detected as new stations, requiring further processing.
Instead of storing the raw binary IDs in the numpy array, store a base64-encoded string, and decode it before passing back to ``InternalPositionSource``.
Fixes #921, which was randomly hitting this issue with Bluetooth stations.

Encode binary IDs in base64 for numpy

---

ichnaea/conftest.py
ichnaea/data/tests/test_public.py
ichnaea/data/tests/test_station.py
ichnaea/db.py

*Note*: This is an alternate implementation of PR #1012. Notes about the differences are at the bottom. This is follow-on work for issue #991.
*Note 2*: Reworked and force pushed, new PR summary.
Previously, all tests used independent sessions bound to a transaction. This fails when a test needs to setup data in the test, and then tests code that issues a transaction rollback. This results in the setup data being rolled back as well. This is currently one test, the recently refactored test for deadlocks in ``StationUpdater``, but more are expected as we add more deadlock handlers.
The Database class now takes a ``shared=True`` keyword. When set, SQLAlchemy's ``scoped_session`` is used to return a thread-local session when ``db.session()`` is called. For these shared sessions, …

Add shared session fixtures

---

ichnaea/data/station.py
ichnaea/data/tests/test_station.py
requirements/default.txt

Add new dependency [backoff](https://github.com/litl/backoff), which provides a ``backoff.on_exception`` decorator that can be used to handle retrying for exceptions. This may help standardize the retry logic before we roll it out to other updater tasks.
I wasn't able to use ``backoff.on_exception`` as a traditional decorator, because the ``METRICS`` call needs access to both ``self.station_type`` and the error number from the exception. If I dropped the metrics call, or made it a counter without tags, then it could be simplified down to a decorator.
This is follow-on work for issue #991.

StationUpdater: Use backoff.on_exception decorator

---

ichnaea/data/station.py

When ``SELECT``ing station rows for updating, use ``WITH UPDATE`` to acquire a row lock. This may result in more lock timeouts, but less ``StaleDataError``s in stage and production. If this helps reduce issue #990, then we can roll out a similar change to the cell area and datamap update tasks.

StationUpdater: Use SELECT ... WITH UPDATE

---

ichnaea/api/locate/tests/base.py
ichnaea/api/submit/tests/base.py
ichnaea/api/views.py
ichnaea/data/export.py
ichnaea/queue.py
ichnaea/tests/test_util.py
ichnaea/util.py

For ``util.encode_gzip``, drop optional ``encoding`` parameter and require that the input is bytes. This simplifies half of the callers, and calling ``.encode()`` on the string data does the right thing for the rest.
For ``utils.decode_gzip``, drop the optional ``encoding`` parameter and return the decompressed bytes instead of a string decoded from UTF-8. This simplifies most callers, who were sending ``encoding=None`` to get this behavior.
Also, use Python 3.2's ``gzip.compress`` and ``gzip.decompress``, which take care of the details of feeding bytes through ``GzipFile``. However, errors in the bytes are still raised as if they come from a file, like ``gzip.BadGzipFile``, so the exception handler remains complex.

bug 1607906: Remove string handling from encode/decode_gzip

---

docs/metrics.rst
ichnaea/conftest.py
ichnaea/data/area.py
ichnaea/data/datamap.py
ichnaea/data/station.py
ichnaea/data/tests/test_station.py
ichnaea/db.py
ichnaea/tests/test_db.py

Move ``_retry_updates_on_mysql_lock_fail``  to ``retry_on_mysql_lock_fail`` in ``ichnaea.db``, move station-specific stuff to parameters, and implement as a standard decorator.
This makes it a little more awkward to use in ``StationUpdater``, but allows it to be expanded to cell area and datamap updating. This addresses issue #991.
The ``data.station.dberror`` metric may have tag ``type=cellarea`` for retryable
exceptions in ``CellAreaUpdater``, and a new metric ``datamaps.dberror`` is
incremented from ``DataMapUpdater``.
Add a ``WITH UPDATE`` clause to the ``SELECT`` for cell areas and datamaps, to avoid ``StaleDataErrors``s, and maybe turn some into deadlocks (which will now be retried). This addresses issue #990.

Expand lock retries and SELECT ... WITH UPDATE to cell area and datamap updates 

---

docs/api/index.rst
ichnaea/api/exceptions.py
ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_fallback.py
ichnaea/api/locate/views.py
ichnaea/api/submit/tests/base.py
ichnaea/api/submit/tests/test_submit_v0.py
ichnaea/api/submit/tests/test_submit_v2.py
ichnaea/api/submit/views.py
ichnaea/api/tests.py
ichnaea/api/views.py

PR #1028 unintentionally removed an exception handler for string decoding issues. Previously, bytes were decoded as part of ``json.loads``:
https://github.com/mozilla/ichnaea/blob/cc3d9f314110c4acb9af6161f9998b7f06490048/ichnaea/api/views.py#L106-L110
If decoding failed, a ``UnicodeDecodeError`` was raised, which is derived from ``ValueError``, so it was caught and handled.
In Python 3.8, ``json.loads`` no longer uses the `encoding` parameter, so bytes decoding was moved to a separate step, without a ``try``/``except`` block. Some callers have triggered this, raising a handful of exceptions in production (see [bug 1607906](https://bugzilla.mozilla.org/show_bug.cgi?id=1607906#c2)). The most common root cause appears to be sending a truncated gzip-compressed payload, which resulted in an …

bug 1607906: re-write preprocess_request for detailed errors

---

ichnaea/api/views.py
ichnaea/webapp/tests.py
ichnaea/webapp/view.py

Restrict Cross-Origin Resource Sharing, via ``Access-Control-Allow-Origin`` header, to the API endpoints. Previously, CORS was allowed on all views. 
CORS for ``/v1/country`` was requested in November 2015 in https://github.com/mozilla/ichnaea/issues/468. This is appropriate for an API called from in-browser JavaScript from unknown sites, but it doesn't need to be applied to the homepage or other content pages.

bug 1610015: Restrict CORS to API endpoints

---

ichnaea/data/export.py
ichnaea/data/tests/test_export.py

In the ``InternalExporter``, ensure that a position of null/``None`` is dropped without an error. For other exporters, confirm that these reports are forwarded without errors.
In [v2/geosubmit](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html), the position item is a dictionary that includes the latitude and longitude, position source, and other details. It is not
required by the geosubmit endpoints, and it is possible for clients to submit WiFi and other data without including a GPS-derived position.
This fixes [bug 1613233](https://bugzilla.mozilla.org/show_bug.cgi?id=1613233), where a null position was causing an exception to be raised.

bug 1613233: Drop reports with null positions

---

ichnaea/geoip.py
ichnaea/webapp/monitor.py
ichnaea/webapp/tests.py

This adds the maxmind db `build_epoch` to the `__heartbeat__` response as geoip version.
To test:
```
curl http://localhost:8000/__heartbeat__
```

bug 1616536: add geoip version to __heartbeat__

---

ichnaea/geoip.py
ichnaea/webapp/tests.py

The version is a seconds-since-epoch of the build. This changes it to a
`YYYY-MM-DDTHH:MM:SSZ` format which is what Telemetry uses.

bug 1616536: change format of maxmind db version in /__heartbeat__

---

docker/node/Dockerfile

Major Changes No 1 : debian package manager tweaks
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Major Changes No 2 : added packages apt-utils ca-certificates
Because build is 
1.  Slow and in log it is showing because "apt-utils" not installed 
2. to avoid build to exits with error without having certificate

Enhancement debian package manager tweaks

---

ichnaea/content/templates/api.pt

This adds a separate section for Mozilla projects because we have a different way for them to request API keys.

bug 1619789: add API key request instructions for Mozilla projects

---

.circleci/config.yml

Update from version 2.0 to 2.1. The main difference appears to be [pipelines](https://circleci.com/docs/2.0/build-processing/).

Update to CircleCI 2.1 format

---

docs/metrics.rst
ichnaea/api/locate/query.py
ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_fallback.py
ichnaea/api/locate/tests/test_internal.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/locate/tests/test_query.py

As discussed on [bug 1623470](https://bugzilla.mozilla.org/show_bug.cgi?id=1623470), the `region` tag leads to InfluxDB query inefficiencies due to high cardinality.  Thanks to @sciurus for the bulk of this code. My changes are for linting and the metrics docs.
Our plan is to move the `region` tag to the logs, and analyze regions with BigQuery.

bug 1623470: Drop region tag from metrics

---

docs/metrics.rst

Follow on for PR #1144. We released the change to drop the region tag in [tag 2020.04.16](https://github.com/mozilla/ichnaea/releases/tag/2020.04.16).

bug 1623470: Set release tag for dropping region

---

ichnaea/webapp/app.py

`expose_tracebacks` will show the traceback when a request raises an exception. Otherwise, a generic "an exception occured" message is returned.
I believe this file is run as ``__main__`` only in development (we use nginx and gunicorn in production, and probably refer directly to `ichnaea.webapp.app.wsgi_app`), but I based it off the `local_dev_env` setting just in case.

Show tracebacks in local development environment

---

ichnaea/webapp/app.py

When running under gunicorn, use ``log_middleware`` to produce the ``canonical-log-line`` structured logs.
To test locally, I add this to ``my.env``:
```
LOCAL_DEV_ENV=False
```
and then ran ``make run``. Output with a call to ``/v1/country?key=test``:
```
web_1        | {"Timestamp": 1588627191391223296, "Type": "canonical-log-line", "Logger": "ichnaea", "Hostname": "177132d32fa9", "EnvVersion": "2.0", "Severity": 6, "Pid": 19, "Fields": {"http_method": "GET", "http_path": "/v1/country", "api_path": "v1.country", "api_key": "test", "api_type": "region", "region": null, "blue": 0, "blue_valid": 0, "cell": 0, "cell_valid": 0, "wifi": 0, "wifi_valid": 0, "has_geoip": false, "has_ip": true, "source_geoip_accuracy": null, "source_geoip_accuracy_min": "low", "source_geoip_status": "miss", …
```

bug 1632621: Use log_middleware in gunicorn

---

ichnaea/conftest.py
ichnaea/content/tests/test_views.py
ichnaea/log.py
ichnaea/webapp/app.py

PR #1163 added ``log_middleware`` to ``wsgi_app``, so that structured logging was available in deployments with gunicorn as well as development. This takes it a step further and moves logging to ``log_tween_factory``, a "tween" (Pyramid middleware) that already handles request-level metrics and raven exception capturing.
The ``log_tween`` method has quite a few changes:
* The shortcut handler for static assets (served from `/static` or has a `skip_logging` attribute like `/robots.txt`) has been removed and integrated into the rest of the logic. This means some stuff like clearing the structured log and capturing the current time happens for these requests as well, but I was already doing this in ``log_middleware``. I _think_ I got the exception handling logic merged correctly, but if more …

bug 1632621: Move structured logging to log_tween_factory

---

ichnaea/api/locate/query.py
ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/locate/tests/test_region_v1.py
ichnaea/api/submit/tests/base.py
ichnaea/api/views.py
ichnaea/conftest.py
ichnaea/content/tests/test_views.py

Add a pytest fixture ``logs`` that captures the structured logging entries and makes them available for testing. Add full log entry tests for non-API views, basic successful API views, and some error cases. Add targeted log entry tests for API key validation, and some for location to demonstrate the additional testing capabilities.
This also changes the base API view to allow more log metrics:
* submit APIs now have ``api_type="submit"``
* For geolocate and submit APIs, usage metrics are added:
- ``api_key_count``: Daily count of API usage by this key
- ~``api_key_ip_count``~: ~Daily count of API usage by this key and IP~
- ``api_key_repeat_ip``: True if we've seen this API key / IP combo today (using Redis [HyperLogLog](https://redislabs.com/redis-best-practices/counting/hyperloglog/))~ …

bug 1632621: Test structured logging, expand API logging

---

docker/config/test.env
docs/deploy.rst
ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/locate/views.py
ichnaea/conf.py
ichnaea/tests/test_conf.py
ichnaea/tests/test_util.py
ichnaea/util.py
ichnaea/webapp/config.py

Add a ``SECRET_KEY`` configuration setting, used in a similar way to Django's [SECRET_KEY](https://docs.djangoproject.com/en/3.0/ref/settings/#secret-key) as a cryptographic hashing salt. If the web server detects it is not in the development environment, it fails if ``SECRET_KEY`` is set to the non-default value.
Use it to create a response signature, which will be the same for the same combo of response JSON, client IP, API path, and API key. Use [Redis PFADD](https://redis.io/commands/pfadd) to detect unique and repeated responses. Add two new log metrics:
* ``api_repeat_response`` - ``True`` if this response was repeated
* ``api_response_sig`` - The first 8 hex digits of the response signature

bug 1635789 - Add SECRET_KEY, response signature

---

ichnaea/api/locate/views.py

Collecting all responses in a single [PFADD](https://redis.io/commands/pfadd) structure lead to a high percentage of false positives for API keys with relatively low traffic. Splitting by API type and API key mirrors the `PFADD` structure used to [detect repeated IP addresses](https://github.com/mozilla/ichnaea/blob/7a7ad8d7f81edc21b8e71573746dbb5004fb072d/ichnaea/api/views.py#L76-L79), and should be more accurate for the long tail of API keys.
When using the single `PFADD`, there is a high percent of "bizarre" requests, where `api_key_repeat_ip` is False (this IP has not been seen today for this API / API Key) but `api_repeat_response` is True (this IP requested with this API / API Key and got the same response). Overall, 0.07% of the responses are bizarre, and 0.03% of the GeoClue …

bug 1635789: Count repeated responses per API key

---

ichnaea/api/locate/tests/base.py
ichnaea/api/locate/tests/test_locate_v1.py
ichnaea/api/locate/views.py
ichnaea/api/submit/tests/base.py
ichnaea/api/views.py

The metrics ``api_key_repeat_ip`` and ``api_repeat_response`` are based on the
return from [PFADD](https://redis.io/commands/pfadd), used to estimate the number of daily unique IP addresses and responses. After further research, this does not signify if a value is a repeat, but if the estimated cardinality has changed. This is less and less frequent as the cardinality increases, exceeding 99% at 100 million items. This is not a useful metric to track.
The cardinality of the IP addresses is useful, so the related ``PFADD`` call is retained, without capturing the return. The [PFCOUNT](https://redis.io/commands/pfcount) return, accurate to about 1%, is still sent [as an operational metric](https://github.com/mozilla/ichnaea/blob/b3f523a8bc6bc20f310317b7cd19c45c460edd15/ichnaea/data/monitor.py …

bug 1635789: Remove PFADD log metrics

---

.circleci/config.yml
CONTRIBUTING.rst
bin/release.py
docs/api/index.rst
docs/api/region.rst
docs/conf.py
docs/configure.rst
docs/dataflows.rst
docs/debug.rst
docs/deploy.rst
docs/local_dev.rst
ichnaea/taskapp/config.py
setup.cfg

Update the configuration and documentation for today's change of making the new `main` branch the default branch (see [this blog post](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx), as well as some other updates:
* In CircleCI, take special actions like uploading docker images on the `main` rather than `master` branch
* Update `bin/release.py` to latest version that supports different default branches, plus a line length change
* Update documentation references and code comments to the `main` branch of Ichnaea
* Bump copyright to 2020
* Fix some URLs and surrounding docs that failed `make linkcheck` validation
Addition, non-code changes are also needed, see [bug 1647364](https://bugzilla.mozilla.org/show_bug.cgi?id=1647364) for tracking.

bug 1647364: Switch default branch from master to main

---

docs/conf.py
requirements/default.txt
requirements/docs.txt
requirements/shared.txt

Split documentation dependencies so that they can be installed in ReadTheDocs. This will allow us to use Sphinx 3.0.4 in both dev and in RTD.
The change in PR #1220 broken documentation builds, because RTD uses Sphinx 1.8.5 by default, and I was relying on a change in 2.0. I also followed the [FAQ](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs) to use the default RTD theme in RTD.

bug 1647364: Install Sphinx 3 in RTD

---

.readthedocs.yml
docs/requirements.txt

I missed that we already had a solution that installed requirements. This builds on PR #1222, to switch the ReadTheDocs config to use the new refactored ``requirements/docs.txt``.

bug 1647364: Use the new refactored requirements/docs.txt

---

ichnaea/data/tests/test_export.py

Use ``pytest.approx`` to ignore small float differences when round-tripping with PyMySQL 0.10.0.

bug 1657408: Use pytest.approx for export tests

---

docker/run_lint.sh
docs/conf.py
geocalclib/setup.py

I keep my Python virtualenvs in the root of the repository, so a bare `pyflakes8` or `black` will try to lint everything I have installd -- no fun.
It seems like black skips a few files by default, too, that are now covered, and are updated in this PR (just changing quote symbols).

run lint over specific directories, fix black issues

---

ichnaea/content/views.py

With this change, all unhandled 404's are captured and display a simple "404 Not Found" headline, overriding Pyramid's default handling.

Bug 1272068 - Add a blanket 404 handler that does not echo the path

---

docs/metrics.rst

Rewrite the metrics document and expand it to cover structured logs:
* Describe the difference between statsd metrics and structured logging
* Create an Implementation section, to describe our implementation, the issues around high cardinality, and that this is all in progress
* Instead of the narrative flow, split up metrics by web app, task app, and datamaps, with some secondary sections as needed, and a new section for web app structured logs.
* Split up metrics to a section per metric, with a new style for documenting tags, and with cross-references to structure logs
* Reorganize backend and pipeline sections, and add more context. Some of this is duplicated on the data flows page, and could be merged.
All of this makes the diff view fairly useless for reviewing this change (except …

1632621: Rewrite metrics doc for structured logs

---

.dependabot/config.yml
.github/dependabot.yml

Switch from the dependabot-preview spec to the current version.
Based on https://github.com/mozilla-services/antenna/pull/635. @willkg does this look correct?

Switch to dependabot v2

---

.circleci/config.yml

As discussed [here](https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572), CircleCI is deprecating older machine images. This includes the image
``docker-17.09.0-ce image``, which is the default for the ``"setup_remote_docker"`` step. Replace it with ~(the recommended Ubuntu 16.04 image)~ 19.03.13, the [latest available version](https://circleci.com/docs/2.0/building-docker-images/#docker-version) and the one I'm running locally.

CircleCI config updates: Specify remote docker image

---

.circleci/config.yml

Apply authentication in the ``docker:auth`` section instead of as an explicit shell command during step "Push to Dockerhub". The authenticated connection will also avoid rate limiting for Docker image pulls during the step "Build Docker images".
Maybe.
This investigates the question raised at https://github.com/mozilla/ichnaea/pull/1369#pullrequestreview-502381253, if the login for ``docker: auth`` applies for the full CI run. We may only see the results when it is merged to main and the code attempts to push to Dockerhub. If it works, then the commit message will be correct. Otherwise, we'll need to revert and do something more like PR #1369.

CircleCI: Use docker auth instead of direct login

---

.circleci/config.yml

Starting [November 2020](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/), Dockerhub will limit unauthenticated docker pulls by IP address. Log in before building images, which may pull from DockerHub, using [a setup](https://circleci.com/docs/2.0/private-images/) suggested by CircleCI, and building on login before pushing tags.

Login to docker before building images

---

CONTRIBUTING.rst
contribute.json
docker/node/package.json
ichnaea/content/templates/contact.pt
setup.py

For issue #1406, replace most links to the [dev-geolocation mailing list](https://lists.mozilla.org/listinfo/dev-geolocation) with links to the [Location category](https://discourse.mozilla.org/c/location/506) on Discourse. For other instances, just remove the link or the mailing list email address.
Also, add a link to the [location chat room](https://chat.mozilla.org/#/room/#location:mozilla.org). I will try to remember to check it periodically.
For issue #1374, switch the text to prefer GitHub issues, but use Bugzilla for confidential and security issues.

Updates for new mailing list and preferred issue tracker

---

Dockerfile

``scipy`` fails to build under Python 3.9, because wheels are not yet ready and the source build can't load lapack/blas resources:
```
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
```
This adds the ``gfortran``, ``liblapack-dev``, and ``libatlas-base-dev`` libraries, needed to build from source, as seen in the [bleeding edge](https://github.com/scipy/scipy/blob/master/.github/workflows/bleedingedge.yml#L32) build.

issue #1417: Add libs for scipy and Py 3.9

---

setup.cfg

Dependabot may use this as a hint to use Python 3.6 when determining what requirements to install. 
See issue #1428.

Specify Python 3.6 or later

---

setup.py

As a possible solution to issue #1428, Dependabot may use this file as a clue to use Python 3 instead of 2.

Bring back setup.py

---

requirements-docs.txt

Just specifying `Sphinx` is not enough, because RTD installs `Sphinx < 2` first.
This broke while trying to fix issue #1428.

Use Sphinx 3.2.1 in Read the Docs

---

requirements-docs.txt
requirements.in
requirements.txt

* colorama 0.4.3 → 0.4.4: Fix OSC regex, project changes
* factory-boy 3.0.1 → 3.1.0: Fix for importing framework-specific
factories
* pip-tools 5.3.1 → 5.4.0: pip 20.3 support
* pytest 6.1.1 → 6.1.2: Bug fixes
* sphinx 3.2.1 → 3.3.1: Bug fixes, deprecations

Dependency Updates, December 2020, Round 2: Development dependencies

---

requirements.in
requirements.txt

* boto3 1.15.11 → 1.16.30: AWS changes
* celery[redis] 5.0.0 → 5.0.3: Bug fixes
- Regression: When using the prefork pool, pick the fair scheduling strategy by default 🤔 might have something to do with our perf changes when switching to 5.0.0 (see #1398)
* colander 1.8.2 → 1.8.3: Python 3.9 support
* dockerflow 2020.6.0 → 2020.10.0: Sanic and Flask updates
* everett 1.0.2 → 1.0.3: Python support updates
* maxminddb 2.0.2 → 2.0.3: mmap is optional again
* more-itertools 8.5.0 → 8.6.0: Python support updates, new tools
* numpy 1.19.2 → 1.19.4: Python 3.9 binary wheels 🎉 , OpenBLAS fixes
* pyramid 1.10.4 → 1.10.5: Python support updates
* pytz 2020.1 → 2020.4: Still messing with timezones
* requests 2.24.0 → 2.25.0: Support urllib3 1.26
- Deprecates [security] extra 🤭 - pyopenssl may be on …

Dependency Updates, December 2020, Round 3: Production dependencies

---

docs/metrics.rst
docs/rate_control.rst

As part of setting up dashboards for issue #1398, I noticed some issues in new and old documents.
``request.timing`` says it has the same ``status`` tag as ``request``, but it doesn't. I considered adding the tag to ``request.timing``, but we can do similar analysis with log data and BigQuery. Updated the documentation to reflect the code.
The rate control document cross-linked to references in the metrics document and vice-versa, which requires the Sphinx `:ref:` directive. With the `underscore_` method, the links were unchecked 404 links. `:ref:` added and anchors fixed or adjusted.

Documentation fixes

---

.github/dependabot.yml
docker/node/Dockerfile

Update node from 8.x to 14.x (issue #1390), with no package updates. Enable Dependabot for the Dockerfile and for the npm packages.
Node is used to install javascript libraries like jquery and mapbox, and to combine and minify CSS and JS for the website. It is not run in production.

Update from node 8.x to 14.x

---

ichnaea/api/key.py
ichnaea/conftest.py
requirements.in
requirements.txt

[cachetools.TTLCache](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache) is a least-recently-used cache that also has a time-to-live (TTL) for entries. It seems to have the same function as [repoze.lru.ExpiringLRUCache](https://github.com/repoze/repoze.lru/blob/master/repoze/lru/__init__.py#L178), however [repoze.lru](https://github.com/repoze/repoze.lru) has not seen updates in 3 years and is no longer used by Pyramid.
cachetools has a flexible [@cached decorator](https://cachetools.readthedocs.io/en/stable/#cachetools.cached) that can be used to memoize ``get_key`` without the manual cache manipulation. It is not thread-safe by default, so the code now uses gevent's [RLock](http://www.gevent.org/api/gevent.lock.html#gevent.lock.RLock) to synchronize access.
Fixes #919

Replace ExpiringLRUCache with TTLCache

---

ichnaea/api/submit/tests/test_submit_v0.py
ichnaea/models/sa_types.py
requirements.in
requirements.txt

For issue #1440, replace a few more instances of ``pytz`` in the code, then remove it from the primary requirements file. ``pytz`` is still used by babel and celery, so it will continue to be installed.

Replace more pytz with zoneinfo

---

mobile_codes/parse.py

In addition to #1421 add an exceptional parsing for British Indian Ocean Territory.
This will replace the null mccs list in the countries.json for "British Indian Ocean Territory" to "995"

parsing for British Indian Ocean Territory

---

ichnaea/log.py
ichnaea/scripts/datamap.py

Update the datamap script with changes from a test run in staging (issue #840):
* Switch from using the high-level [Bucket resource](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#bucket) to the [low-level client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#client) to access the S3 bucket. Others have had problems with [multiprocessing and the S3 Resource interfaces](https://github.com/boto/boto3/issues/1670), which may accumulate memory due to caches or session accumulation. Others have suggested [the low-level client does not share this problem](https://github.com/boto/botocore/issues/1246#issuecomment-589909285). The Amazon devs are sadly quiet.
* Add a ``--verbose`` option to force the logging options used in …

Datamap script: Update logging and switch to low-level S3 client

---

ichnaea/scripts/datamap.py

For issue #840, switching to the low-level S3 client in PR #1480 did not help the out-of-memory messages. Next, I'm trying [maxtasksperchild](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool), hoping that destroying and recreating the task thread will reset memory usage.
Hitting Ctrl-C to halt the script was causing a ``KeyboardInterrupt`` exception to be logged in Sentry. This adds a handler for this event to skip logging to Sentry, and adjusts the final log message if it halted due to an interrupt.
This adds debug log messages for the start of tile creation and upload. Otherwise, there is a long period with no feedback that the script is running.
This updates a few debug log messages to fix pluralization and to more consistently use commas as thousands …

Datamap script: Limit process usage, handle Ctrl-C, more logging tweaks

---

docs/metrics.rst
ichnaea/scripts/datamap.py
ichnaea/scripts/tests/test_datamap.py

**Work in Progress** - These changes are being tested on a production server.
For issue #840, make further changes to the datamap script and documentation:
* When an export CSV reached 10,000,000 rows, start writing to multiple CSV files. These are processed into separate quadtree files, which are then merged (duplicates allowed) into the per-table quadtree files, before being merged (eliminating duplicates) into a final whole-world quadtree. This should avoid out-of-memory errors when converting a very large tables from CSV to a quadtree.
* Adjust database mocking method, so that we can test for the ``generate()`` function and the serialized CSV paths.
* Update documentation for new structured logging data.

Datamap script updates for production

---

docker/node/Dockerfile

Dependabot keeps trying to update to the current node v15 version. I hope that switching to the ``lts-slim`` tag will tell Dependabot to keep updating in the v14 tree until v16 is released.

Switch to lts-slim tag

---

.github/dependabot.yml

Dependabot preview was unlimited after you caught up, and now the default is 5, which is too few for effective monthly updates. With https://github.com/willkg/paul-mclendahand, we can handle all the updates.

Increase dependabot pull request limits

---

ichnaea/api/key.py
ichnaea/db.py

For issue #1569, detect when SQLAlchemy 1.4 constructs are needed for:
* Immutable URL objects
* Row returned rather than RowProxy

SQLAlchemy 1.3 / 1.4 dual mode

---

ichnaea/db.py

Use an empty string instead of ``None`` to clear the database for the generic connection. Use a connection rather than executing directly against the engine. Part of issue #1569.

Fix SQLAlchemy 1.4 DB create/drop

---

docs/import_export.rst

Just fixing a minor typo. The correct term for the coordinate system used by GPS is **WGS** 84, standing for World Geodetic System, not "WSG" 84. reference: https://en.wikipedia.org/wiki/World_Geodetic_System

Fix minor docs typo: WSG 84 -> WGS 84

---

docker/node/Dockerfile

Using ``lts-slim`` as the node tag made it difficult to see what node version is being applied by Dependabot, since the change was just the image hash. Changing back to the version number puts the burden back on the maintainers to stay on the LTS version.
In node news, v14.17.0 is the LTS version, v16 is current, and will become the active LTS version on October 26, 2021. See [Releases](https://nodejs.org/en/about/releases/) for the schedule.

Switch to version number in Dockerfile

---

ichnaea/models/cell.py
ichnaea/models/content.py
ichnaea/models/mac.py

SQLAlchemy 1.4.14 emits a warning without this annotation. Each appear to be cache safe. Part of issue #1569.

Add more `cache_ok` to custom types

---

docs/metrics.rst
docs/rate_control.rst
ichnaea/data/monitor.py
ichnaea/data/tests/test_monitor.py

For issue #1618, update the queue size and rate control task to also look at the InnoDB transaction history length, if the celery task database user has the ``PROCESS`` permission. This is emitted as a new metric ``trx_history.length``.
This history increases with each transaction, and is decreased by a purge process. If the purge process can't keep up, due to the rate of new transactions, or because there is a transaction left open, then the history will increase, eventually requiring the system tablespace to increase. The system tablespace can not be shrunk without recreating the database, so it is important to keep transaction history within bounds.
If the automated rate controller is active, then a maximum and minimum can be set. When the length exceeds the maximum, then location …

Monitor InnoDB transaction history length, pause observation processing

---

docs/local_dev.rst
ichnaea/conftest.py
ichnaea/data/stats.py
ichnaea/db.py
ichnaea/taskapp/task.py

For issue #1620, use "READ COMMITTED" transaction isolation when counting stations by region. In production, the large database means these queries take much longer than other queries, and with the default isolation of "READ COMMITTED", MySQL needs to keep track of transactions from other processes until the ``update_statregion`` task is complete.
This mode does not interact well with tests, which use a transaction paired with a rollback to restore the test database after each test. For tests, the custom ``TestDatabase`` ignores the request for ``READ COMMITTED``.
Since I couldn't use tests to check the feature, I instead ran the task in my development environment, which took longer to figure out then expected. I've added some documentation for running async task workers, as well as the …

Use "READ COMMITTED" transaction isolation when counting stations by region

---

Dockerfile

MySQL [does not provide arm64 binaries](https://repo.mysql.com/apt/debian/dists/buster/mysql-5.7/), but MariaDB client libraries, which [provide a compatible interface](https://mariadb.com/database-topics/mariadb-vs-mysql/), provides arm64 and amd64 binaries and are suggest by `apt-get`. This will allow the same library to be used in development on Intel and Apple Silicon, as well as in production deployments.
Addresses issue #1636.

Switch to MariaDB client libraries

---

ichnaea/conf.py
requirements.in
requirements.txt

* Bump everett from 1.0.3 to 2.0.0 (from PR #1656)
* Update configuration for Everett 2.0. This is mostly rearranging for the new ``Option`` format, but the diff makes it look like a rewrite. The internals of the configuration changed as well, which I peek at to see if the ``SECRET_KEY`` was set in production.

Dependency updates, August 2021, Round 3: Everett 2.0.0

---

docker/node/Dockerfile
docker/node/npm-shrinkwrap.json

According to https://nodejs.org/en/about/releases/, Node 16 (Gallium) became the LTS release on 2021-10-26, will be the active LTS release until 2022-10-18, and will be end-of-life 2024-04-30.

Update to node 16.13.0 LTS

---

docker/node/npm-shrinkwrap.json
docker/node/package.json
requirements.in
requirements.txt

Update dependencies. This covers:
* Bump clean-css-cli from 5.4.2 to 5.5.0 in /docker/node (from PR #1749): Adds ``--watch`` switch
* Bump uglify-js from 3.14.4 to 3.14.5 in /docker/node (from PR #1750): Improve performance
* Bump boto3 from 1.20.26 to 1.20.28 (from PR #1760): More AWS API updates
The NPM tool upgrades did not change the static assets created with ``make assets``.

Dependency updates, January 2022, part 2

---

docs/configure.rst
ichnaea/conf.py
requirements.in
requirements.txt

This includes https://github.com/mozilla/ichnaea/pull/1778, and also:
* Updates `check_config()` to use ``AppComponent.Config`` instead of the undocumented v2 implemention
* Update the documentation with the new `autocomponentconfig` directive

Upgrade everett from 2.0.1 to 3.0.0

---

requirements-docs.txt
requirements.in
requirements.txt

For some reason, Dependabot was unable to perform this upgrade. Tested locally with `make docs`.

Update to Sphinx 4.4.0

---

.circleci/config.yml

The [CircleCI base image](https://circleci.com/developer/images/image/cimg/python) may provide efficiency gains. The [Mozilla base image](https://github.com/mozilla/ci-docker-bases/blob/master/docker/Dockerfile) isn't very different, but may not be maintained in the future.

Switch to CircleCI base image

---

docker-compose.yml

Update to use redis 6.2.7.
Redis's release policy is a new major version once a year, and a minor version after about 6 months. Version 7 is in development, and 5 is the oldest supported version.
https://redis.io/docs/about/releases/

Update to redis 6.2.7

---

ichnaea/conf.py
ichnaea/log.py

The new library, `sentry_sdk`, will pick this environment variable up automatically. We need to explicitly set it for Raven.

Send SENTRY_ENVIRONMENT to Sentry

---

.gitignore
ichnaea/data/tasks.py

Relates to issue https://github.com/mozilla/ichnaea/issues/2043 - the data queues can get backed up causing data to be lost. 
This removes an unnecessary 1 second delay between processing batches of records. On the surface this doesn't seem like much, but in local testing it makes a huge difference and will hopefully alleviate the issue.

Removing 1 second delay for data tasks that are ready to be processed
